repos:
- repo: https://github.com/psf/black
  rev: 24.3.0
  hooks:
    - id: black
      language_version: python3.12
      files: ^backend/
      types: [python]

- repo: local
  hooks:
    - id: prettier
      name: prettier
      entry: cd frontend && pnpm prettier --write
      language: system
      files: ^frontend/.*\.(ts|tsx|js|jsx|css|scss|json)$
      pass_filenames: false