version: "3.8"

services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    command: ["--auth", "--bind_ip_all"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: archspec_user
      MONGO_INITDB_ROOT_PASSWORD: archspec_password
      MONGO_INITDB_DATABASE: archspec

volumes:
  mongo-data:
