services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=archspec_user
      - MONGO_INITDB_ROOT_PASSWORD=archspec_password
      - MONGO_INITDB_DATABASE=archspec
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
