name: Deploy to Digital Ocean

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Deploy to Digital Ocean
        env:
          DROPLET_HOST: ${{ secrets.DROPLET_HOST }}
          DROPLET_USER: ${{ secrets.DROPLET_USER }}
          PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
        run: |
          ssh $DROPLET_USER@$DROPLET_HOST << 'ENDSSH'
            # Navigate to project directory
            cd ${{ secrets.PROJECT_PATH }}
            
            # Pull the latest changes
            git pull
            
            # Create or update .env file for environment variables
            # This assumes you've stored your environment variables in GitHub secrets
            echo "${{ secrets.ENV_FILE }}" > .env
            
            # Add BACKEND_API_URL to the environment variables
            # This sets the API URL for the frontend to use
            echo "BACKEND_API_URL=${{ secrets.BACKEND_API_URL }}" >> .env
            
            # Build and restart the containers using production compose file
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml build --no-cache
            docker-compose -f docker-compose.prod.yml up -d
            
            # Clean up unused images
            docker image prune -f
          ENDSSH
